# Generated by Django 5.0.2 on 2024-02-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first_app", "0002_accessrecord_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrecord",
            name="date",
            field=models.DateField(blank=True),
        ),
    ]
